version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/ruby:2.6.8
    steps:
      - checkout
      - run: bundle install
      - run: rubocop

  spec:
    docker:
      - image: cimg/ruby:2.6.8
    steps:
      - checkout
      - run: bundle install
      - run: rake spec

workflows:
  version: 2
  build:
    jobs:
      - lint
      - spec
